### ISSUE TITLE
The demo doesn't work for me

### ISSUE THREAD

**Issue by JurgenJocubeit** [gauravtiwari/relay-rails-blog#6] opened 2016-06-14 21:24 UTC
https://relay-rails-blog.herokuapp.com just shows a spinner endlessly. I was able to create an user but the posts page (root) never renders. At first I though maybe your heroku instance was asleep, but I'm not sure that's the problem.

BTW excellent series of posts on this subject, very much appreciated.

**Comment by gauravtiwari** [comment] 2016-06-15 03:14
Hey @JurgenJocubeit Thanks for reporting the issue 👍  Are you seeing this on desktop browser?

**Comment by gauravtiwari** [comment] 2016-06-15 03:14
I can reproduce the issue in mobile browsers, investigating...

**Comment by JurgenJocubeit** [comment] 2016-06-15 04:31
I was using latest Safari on Mac OS X. Is working now in both Safari and Chrome.

**Comment by JurgenJocubeit** [comment] 2016-06-15 04:35
This is really excellent work, that demo rocks! Well done and thanks for sharing!

**Comment by JurgenJocubeit** [comment] 2016-06-15 04:39
I just noticed the dates on each post in the posts listing is coming up as "Invalid date".

**Comment by gauravtiwari** [comment] 2016-06-15 05:06
Hey @JurgenJocubeit, Turns out a gem (`local_time`) used for date parsing was causing issue in Safari and Firefox, although strangely, Chrome didn't throw any error. The demo and master branch is now fixed so, feel free to test it out again. 

There was also a login issue, due to turbolinks, and that's also fixed. Please clear out browser cookies, just in case or try in incognito mode to refresh session.

Thanks :)

**Comment by gauravtiwari** [comment] 2016-06-15 05:15
So looks like all working now! Free free to open another issue if you find anything.

**Closed by gauravtiwari** 2016-06-15 05:15 UTC
